name: Fix Layout References

on:
  workflow_dispatch:

jobs:
  fix-layouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fix layout references
        run: |
          # List of files that need updating based on our search
          files=(
            "src/services/residential/blown-in.njk"
            "src/services/residential/crawl-space.njk"
            "src/services/residential/wall.njk"
            "src/services/residential/removal.njk"
            "src/services/commercial/office.njk"
            "src/services/commercial/retail.njk"
            "src/services/commercial/new-construction.njk"
            "src/services/industrial/cold-storage.njk"
            "src/services/industrial/manufacturing.njk"
            "src/services/industrial/equipment.njk"
            "src/services/agricultural/tank.njk"
            "src/services/agricultural/barn.njk"
            "src/services/agricultural/storage.njk"
          )
          
          # Fix each file
          for file in "${files[@]}"; do
            if [ -f "$file" ]; then
              echo "Fixing: $file"
              sed -i 's/layout: service-page\.njk/layout: layouts\/service-page.njk/g' "$file"
            fi
          done
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Fix layout references to use correct path"
          git push
